name: Validate Pull Request

on:
  pull_request:
    branches: [main, dev]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 10.20.1
        uses: actions/setup-node@v1
        with:
          node-version: '10.20.1'
      - run: npm i -g npm@6.14.5
      - run: npm ci
      - run: npm run lint

  test-node:
    runs-on: ubuntu-latest

    services:
      backend:
        image: gravwell/gravwell:latest
        env:
          GRAVWELL_INGEST_SECRET: MyIngestSecret
          GRAVWELL_INGEST_AUTH: MyIngestSecret
          GRAVWELL_CONTROL_AUTH: MyControlSecret
          GRAVWELL_SEARCHAGENT_AUTH: MySearchAgentAuth
        ports:
          - 8080:80

    steps:
      - shell: bash
        env:
          LICENSE: ${{ secrets.TEST_LICENSE }}
        run: |
          [[ "$(echo "$LICENSE" | base64 -d | md5sum)" == "e1fd9a7a78a5ddd27e3443f2144a6de3  -" ]]
          echo "$LICENSE" | base64 -d | curl -F file=@-;filename=license http://localhost:8080/license
          sleep 10
          curl --fail http://localhost:8080/api/test
      - uses: actions/checkout@v2
      - name: Use Node.js 10.20.1
        uses: actions/setup-node@v1
        with:
          node-version: '10.20.1'
      - run: npm i -g npm@6.14.5
      - run: npm ci
      - run: npm run test:node
